name: tests
on: 
  push:

permissions: {}

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: stable
    - name: Install libpcsc
      run: sudo apt-get install -y libpcsclite-dev pcscd pcsc-tools
    - name: Test
      run: "go test -C v2 ./..."

  build-windows:
    name: Windows
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: stable
    - name: Test
      run: "go build -C v2 ./..."
      env:
        CGO_ENABLED: 0
